// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfrTK20yd96vMWUDc3XdLGf6GTGrm9-PY',
    appId: '1:489055004277:web:62ab1eb2ec934c83eaba3c',
    messagingSenderId: '489055004277',
    projectId: 'my-insta-5db4f',
    authDomain: 'my-insta-5db4f.firebaseapp.com',
    storageBucket: 'my-insta-5db4f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4AUnJmcklW5QnjgiBM0kJJrooEq-XJXw',
    appId: '1:489055004277:android:c0b05d1f8d51ab6feaba3c',
    messagingSenderId: '489055004277',
    projectId: 'my-insta-5db4f',
    storageBucket: 'my-insta-5db4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwcYgVENfsspHjmMfAICNOLV5VeHyq_IY',
    appId: '1:489055004277:ios:c04959087d460310eaba3c',
    messagingSenderId: '489055004277',
    projectId: 'my-insta-5db4f',
    storageBucket: 'my-insta-5db4f.appspot.com',
    iosClientId: '489055004277-tavirkp3rphv7q101bca9dbqvck657d4.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwcYgVENfsspHjmMfAICNOLV5VeHyq_IY',
    appId: '1:489055004277:ios:c04959087d460310eaba3c',
    messagingSenderId: '489055004277',
    projectId: 'my-insta-5db4f',
    storageBucket: 'my-insta-5db4f.appspot.com',
    iosClientId: '489055004277-tavirkp3rphv7q101bca9dbqvck657d4.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
